library(shiny)
library(rCharts)
library(reshape)

aalto_all_m <- read.table(file = "aalto.altm.nov.csv", 
                          header = TRUE, 
                          sep = ",", 
                          col.names = c("id", "DOI", "URL", "Altmetric.com_URL", "Year",
                                        "WoS", "Altmetric.com_score", "Mendeley", "Connotea", "CiteULike",
                                        "Readers_count", "GooglePlus", "Facebook", "Any_type_of_posts", "Twitter", 
                                        "Accounts", "Blog_posts", "Videos", "Science_news_outlets", "Delicious_bookmarks", 
                                        "PLOSalm_html_views", "PLOSalm_pdf_views", "PLOSalm_scopus", "pmc_citations", "Topsy_tweets", 
                                        "CrossRef", "Nature", "PubMed", "F1000", "Figshare"),
                          colClasses = c("character", "character", "character", "character", "character",
                                         "integer", "numeric", "integer", "integer", "integer",
                                         "integer", "integer", "integer", "integer", "integer", 
                                         "integer", "integer", "integer", "integer", "integer", 
                                         "integer", "integer", "integer", "integer", "integer", 
                                         "integer", "integer", "integer", "integer", "integer"),
                          stringsAsFactors = FALSE)

#aalto_all_m <- read.table(file = "aalto.altm.csv", 
#                          header = TRUE, 
#                          sep = ",", 
#                          col.names = c("id", "DOI", "URL", "Altmetric.com_URL", "Year",
#                                        "WoS", "Altmetric.com_score", "Mendeley", "Connotea", "CiteULike",
#                                        "Readers_count", "GooglePlus", "Facebook", "Any_type_of_posts",
#                                        "Twitter", "Accounts", "Blog_posts", "Videos", "Science_news_outlets",
#                                        "Delicious_bookmarks", "PLOSalm_html_views", "PLOSalm_pdf_views", "PLOSalm_scopus",                                       "pmc_citations",
#                                        "Topsy_tweets", 
#                                        "Bloglines", "CrossRef", "Nature", "Postgenomic", "PubMed", "ScienceSeeker", "F1000", "Figshare"),
#                          colClasses = c("character", "character", "character", "character", "character",
#                                         "integer", "numeric", "integer", "integer", "integer",
#                                         "integer", "integer", "integer", "integer",
#                                         "integer", "integer", "integer", "integer", "integer",
#                                         "integer", "integer", "integer", "integer", "integer",
#                                         "integer", "integer", "integer", "integer", "integer", "integer", "integer", "integer"),
#                          stringsAsFactors = FALSE)


allmetrics <- c("Altmetric score (ALT)" = "Altmetric.com_score",
                "Any type of posts (ALT)" = "Any_type_of_posts",
                "Blog posts (ALT)" = "Blog_posts",
                "CiteULike (ALT)" = "CiteULike",
                "Connotea (ALT)" = "Connotea",
                "CrossRef (PLoS)" = "CrossRef",
                "Delicious (IS)" = "Delicious_bookmarks",
                "Facebook (ALT)" = "Facebook",
                "Figshare (PLoS)" = "Figshare",
                "F1000 (PLoS)" = "F1000",
                "Google+ (ALT)" = "GooglePlus",
                "Mendeley (ALT)" = "Mendeley",
                "Nature (PLoS)" = "Nature",
                "PLOS ALM html views (IS)" = "PLOSalm_html_views",
                "PLOS ALM pdf views (IS)" = "PLOSalm_pdf_views",
                "PLOS ALM Scopus (IS)" = "PLOSalm_scopus",
                "PubMed (PLoS)" = "PubMed",
                "Science news outlets (ALT)" = "Science_news_outlets",
                "Topsy tweets (IS)" = "Topsy_tweets",
                "Twitter (ALT)" = "Twitter",
                "Web of Science" = "WoS",
                "Videos (ALT)" = "Videos")

#allmetrics <- c("Altmetric score (ALT)" = "Altmetric.com_score",
#                "Any type of posts (ALT)" = "Any_type_of_posts",
#                "Blog posts (ALT)" = "Blog_posts",
#                "Bloglines (PLoS)" = "Bloglines",
#                "CiteULike (ALT)" = "CiteULike",
#                "Connotea (ALT)" = "Connotea",
#                "CrossRef (PLoS)" = "CrossRef",
#                "Delicious (IS)" = "Delicious_bookmarks",
#                "Facebook (ALT)" = "Facebook",
#                "Figshare (PLoS)" = "Figshare",
#                "F1000 (PLoS)" = "F1000",
#                "Google+ (ALT)" = "GooglePlus",
#                "Mendeley (ALT)" = "Mendeley",
#                "Nature (PLoS)" = "Nature",
#                "PLOS ALM html views (IS)" = "PLOSalm_html_views",
#                "PLOS ALM pdf views (IS)" = "PLOSalm_pdf_views",
#                "PLOS ALM Scopus (IS)" = "PLOSalm_scopus",
#                "Postgenomic (PLoS)" = "Postgenomic",
#                "PubMed (PLoS)" = "PubMed",
#                "Science news outlets (ALT)" = "Science_news_outlets",
#                "ScienceSeeker (PLoS)" = "ScienceSeeker",
#                "Topsy tweets (IS)" = "Topsy_tweets",
#                "Twitter (ALT)" = "Twitter",
#                "Web of Science" = "WoS",
#                "Videos (ALT)" = "Videos")
